version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.linux
    ports:
      - "5000:5000"
    environment:
      GO_HOST: 127.0.0.1
      GO_PORT: 5000
      GO_DB_PATH: /data/links.db
    volumes:
      - go-data:/data

volumes:
  go-data: {}
